from node:20

WORKDIR /judge/
RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get install time
entrypoint ["/bin/bash", "-c", "/bin/time -q -o /judge/output_time -f \"%e %M\" node --stack-size=65536 /judge/Answer.js < /judge/input > /judge/output_run"]